package xyz.przemyk.real_minerals.datagen;

import net.minecraft.data.*;
import net.minecraft.item.crafting.Ingredient;
import net.minecraft.util.ResourceLocation;
import xyz.przemyk.real_minerals.init.RealMinerals;

import java.util.function.Consumer;

public class Recipes extends RecipeProvider {
    public Recipes(DataGenerator generatorIn) {
        super(generatorIn);
    }

    @Override
    protected void registerRecipes(Consumer<IFinishedRecipe> consumer) {
        CrusherRecipeBuilder.crushingRecipe(Ingredient.fromTag(ItemTags.ORES_COPPER), RealMinerals.COPPER_DUST.get(), 2).build(consumer, new ResourceLocation(RealMinerals.MODID, "copper_dust_from_ore"));
        CrusherRecipeBuilder.crushingRecipe(Ingredient.fromTag(ItemTags.INGOTS_COPPER), RealMinerals.COPPER_DUST.get()).build(consumer, new ResourceLocation(RealMinerals.MODID, "copper_dust_from_ingot"));
        CookingRecipeBuilder.blastingRecipe(Ingredient.fromTag(ItemTags.ORES_COPPER), RealMinerals.COPPER_INGOT.get(), 0.7F, 100).addCriterion("has_copper_ore", hasItem(ItemTags.ORES_COPPER)).build(consumer,   new ResourceLocation(RealMinerals.MODID, "copper_ingot_from_blasting_ore"));
        CookingRecipeBuilder.smeltingRecipe(Ingredient.fromTag(ItemTags.ORES_COPPER), RealMinerals.COPPER_INGOT.get(), 0.7F, 200).addCriterion("has_copper_ore", hasItem(ItemTags.ORES_COPPER)).build(consumer,   new ResourceLocation(RealMinerals.MODID, "copper_ingot_from_smelting_ore"));
        CookingRecipeBuilder.blastingRecipe(Ingredient.fromTag(ItemTags.DUSTS_COPPER), RealMinerals.COPPER_INGOT.get(), 0.7F, 100).addCriterion("has_copper_ore", hasItem(ItemTags.DUSTS_COPPER)).build(consumer, new ResourceLocation(RealMinerals.MODID, "copper_ingot_from_blasting_dust"));
        CookingRecipeBuilder.smeltingRecipe(Ingredient.fromTag(ItemTags.DUSTS_COPPER), RealMinerals.COPPER_INGOT.get(), 0.7F, 200).addCriterion("has_copper_ore", hasItem(ItemTags.DUSTS_COPPER)).build(consumer, new ResourceLocation(RealMinerals.MODID, "copper_ingot_from_smelting_dust"));
        ShapedRecipeBuilder.shapedRecipe(RealMinerals.COPPER_INGOT.get()).key('#', ItemTags.NUGGETS_COPPER).patternLine("###").patternLine("###").patternLine("###").addCriterion("has_copper_nugget", hasItem(ItemTags.NUGGETS_COPPER)).build(consumer, new ResourceLocation(RealMinerals.MODID, "copper_ingot_from_nuggets"));
        ShapedRecipeBuilder.shapedRecipe(RealMinerals.COPPER_BLOCK.ITEM.get()).key('#', ItemTags.INGOTS_COPPER).patternLine("###").patternLine("###").patternLine("###").addCriterion("has_copper_ingot", hasItem(ItemTags.INGOTS_COPPER)).build(consumer, new ResourceLocation(RealMinerals.MODID, "copper_block_from_ingots"));
        ShapelessRecipeBuilder.shapelessRecipe(RealMinerals.COPPER_INGOT.get(), 9).addIngredient(ItemTags.STORAGE_COPPER).addCriterion("has_copper_block", hasItem(ItemTags.STORAGE_COPPER)).build(consumer, new ResourceLocation(RealMinerals.MODID, "copper_ingot_from_block"));
        ShapelessRecipeBuilder.shapelessRecipe(RealMinerals.COPPER_NUGGET.get(), 9).addIngredient(ItemTags.INGOTS_COPPER).addCriterion("has_copper_ingot", hasItem(ItemTags.INGOTS_COPPER)).build(consumer, new ResourceLocation(RealMinerals.MODID, "copper_nugget_from_ingot"));

        CrusherRecipeBuilder.crushingRecipe(Ingredient.fromTag(ItemTags.ORES_LEAD), RealMinerals.LEAD_DUST.get(), 2).build(consumer, new ResourceLocation(RealMinerals.MODID, "lead_dust_from_ore"));
        CrusherRecipeBuilder.crushingRecipe(Ingredient.fromTag(ItemTags.INGOTS_LEAD), RealMinerals.LEAD_DUST.get()).build(consumer, new ResourceLocation(RealMinerals.MODID, "lead_dust_from_ingot"));
        CookingRecipeBuilder.blastingRecipe(Ingredient.fromTag(ItemTags.ORES_LEAD), RealMinerals.LEAD_INGOT.get(), 0.7F, 100).addCriterion("has_lead_ore", hasItem(ItemTags.ORES_LEAD)).build(consumer,   new ResourceLocation(RealMinerals.MODID, "lead_ingot_from_blasting_ore"));
        CookingRecipeBuilder.smeltingRecipe(Ingredient.fromTag(ItemTags.ORES_LEAD), RealMinerals.LEAD_INGOT.get(), 0.7F, 200).addCriterion("has_lead_ore", hasItem(ItemTags.ORES_LEAD)).build(consumer,   new ResourceLocation(RealMinerals.MODID, "lead_ingot_from_smelting_ore"));
        CookingRecipeBuilder.blastingRecipe(Ingredient.fromTag(ItemTags.DUSTS_LEAD), RealMinerals.LEAD_INGOT.get(), 0.7F, 100).addCriterion("has_lead_ore", hasItem(ItemTags.DUSTS_LEAD)).build(consumer, new ResourceLocation(RealMinerals.MODID, "lead_ingot_from_blasting_dust"));
        CookingRecipeBuilder.smeltingRecipe(Ingredient.fromTag(ItemTags.DUSTS_LEAD), RealMinerals.LEAD_INGOT.get(), 0.7F, 200).addCriterion("has_lead_ore", hasItem(ItemTags.DUSTS_LEAD)).build(consumer, new ResourceLocation(RealMinerals.MODID, "lead_ingot_from_smelting_dust"));
        ShapedRecipeBuilder.shapedRecipe(RealMinerals.LEAD_INGOT.get()).key('#', ItemTags.NUGGETS_LEAD).patternLine("###").patternLine("###").patternLine("###").addCriterion("has_lead_nugget", hasItem(ItemTags.NUGGETS_LEAD)).build(consumer, new ResourceLocation(RealMinerals.MODID, "lead_ingot_from_nuggets"));
        ShapedRecipeBuilder.shapedRecipe(RealMinerals.LEAD_BLOCK.ITEM.get()).key('#', ItemTags.INGOTS_LEAD).patternLine("###").patternLine("###").patternLine("###").addCriterion("has_lead_ingot", hasItem(ItemTags.INGOTS_LEAD)).build(consumer, new ResourceLocation(RealMinerals.MODID, "lead_block_from_ingots"));
        ShapelessRecipeBuilder.shapelessRecipe(RealMinerals.LEAD_INGOT.get(), 9).addIngredient(ItemTags.STORAGE_LEAD).addCriterion("has_lead_block", hasItem(ItemTags.STORAGE_LEAD)).build(consumer, new ResourceLocation(RealMinerals.MODID, "lead_ingot_from_block"));
        ShapelessRecipeBuilder.shapelessRecipe(RealMinerals.LEAD_NUGGET.get(), 9).addIngredient(ItemTags.INGOTS_LEAD).addCriterion("has_lead_ingot", hasItem(ItemTags.INGOTS_LEAD)).build(consumer, new ResourceLocation(RealMinerals.MODID, "lead_nugget_from_ingot"));

        CrusherRecipeBuilder.crushingRecipe(Ingredient.fromTag(ItemTags.ORES_MAGNESIUM), RealMinerals.MAGNESIUM_DUST.get(), 2).build(consumer, new ResourceLocation(RealMinerals.MODID, "magnesium_dust_from_ore"));
        CrusherRecipeBuilder.crushingRecipe(Ingredient.fromTag(ItemTags.INGOTS_MAGNESIUM), RealMinerals.MAGNESIUM_DUST.get()).build(consumer, new ResourceLocation(RealMinerals.MODID, "magnesium_dust_from_ingot"));
        CookingRecipeBuilder.blastingRecipe(Ingredient.fromTag(ItemTags.ORES_MAGNESIUM), RealMinerals.MAGNESIUM_INGOT.get(), 0.7F, 100).addCriterion("has_magnesium_ore", hasItem(ItemTags.ORES_MAGNESIUM)).build(consumer,   new ResourceLocation(RealMinerals.MODID, "magnesium_ingot_from_blasting_ore"));
        CookingRecipeBuilder.smeltingRecipe(Ingredient.fromTag(ItemTags.ORES_MAGNESIUM), RealMinerals.MAGNESIUM_INGOT.get(), 0.7F, 200).addCriterion("has_magnesium_ore", hasItem(ItemTags.ORES_MAGNESIUM)).build(consumer,   new ResourceLocation(RealMinerals.MODID, "magnesium_ingot_from_smelting_ore"));
        CookingRecipeBuilder.blastingRecipe(Ingredient.fromTag(ItemTags.DUSTS_MAGNESIUM), RealMinerals.MAGNESIUM_INGOT.get(), 0.7F, 100).addCriterion("has_magnesium_ore", hasItem(ItemTags.DUSTS_MAGNESIUM)).build(consumer, new ResourceLocation(RealMinerals.MODID, "magnesium_ingot_from_blasting_dust"));
        CookingRecipeBuilder.smeltingRecipe(Ingredient.fromTag(ItemTags.DUSTS_MAGNESIUM), RealMinerals.MAGNESIUM_INGOT.get(), 0.7F, 200).addCriterion("has_magnesium_ore", hasItem(ItemTags.DUSTS_MAGNESIUM)).build(consumer, new ResourceLocation(RealMinerals.MODID, "magnesium_ingot_from_smelting_dust"));
        ShapedRecipeBuilder.shapedRecipe(RealMinerals.MAGNESIUM_INGOT.get()).key('#', ItemTags.NUGGETS_MAGNESIUM).patternLine("###").patternLine("###").patternLine("###").addCriterion("has_magnesium_nugget", hasItem(ItemTags.NUGGETS_MAGNESIUM)).build(consumer, new ResourceLocation(RealMinerals.MODID, "magnesium_ingot_from_nuggets"));
        ShapedRecipeBuilder.shapedRecipe(RealMinerals.MAGNESIUM_BLOCK.ITEM.get()).key('#', ItemTags.INGOTS_MAGNESIUM).patternLine("###").patternLine("###").patternLine("###").addCriterion("has_magnesium_ingot", hasItem(ItemTags.INGOTS_MAGNESIUM)).build(consumer, new ResourceLocation(RealMinerals.MODID, "magnesium_block_from_ingots"));
        ShapelessRecipeBuilder.shapelessRecipe(RealMinerals.MAGNESIUM_INGOT.get(), 9).addIngredient(ItemTags.STORAGE_MAGNESIUM).addCriterion("has_magnesium_block", hasItem(ItemTags.STORAGE_MAGNESIUM)).build(consumer, new ResourceLocation(RealMinerals.MODID, "magnesium_ingot_from_block"));
        ShapelessRecipeBuilder.shapelessRecipe(RealMinerals.MAGNESIUM_NUGGET.get(), 9).addIngredient(ItemTags.INGOTS_MAGNESIUM).addCriterion("has_magnesium_ingot", hasItem(ItemTags.INGOTS_MAGNESIUM)).build(consumer, new ResourceLocation(RealMinerals.MODID, "magnesium_nugget_from_ingot"));

        CrusherRecipeBuilder.crushingRecipe(Ingredient.fromTag(ItemTags.ORES_NICKEL), RealMinerals.NICKEL_DUST.get(), 2).build(consumer, new ResourceLocation(RealMinerals.MODID, "nickel_dust_from_ore"));
        CrusherRecipeBuilder.crushingRecipe(Ingredient.fromTag(ItemTags.INGOTS_NICKEL), RealMinerals.NICKEL_DUST.get()).build(consumer, new ResourceLocation(RealMinerals.MODID, "nickel_dust_from_ingot"));
        CookingRecipeBuilder.blastingRecipe(Ingredient.fromTag(ItemTags.ORES_NICKEL), RealMinerals.NICKEL_INGOT.get(), 0.7F, 100).addCriterion("has_nickel_ore", hasItem(ItemTags.ORES_NICKEL)).build(consumer,   new ResourceLocation(RealMinerals.MODID, "nickel_ingot_from_blasting_ore"));
        CookingRecipeBuilder.smeltingRecipe(Ingredient.fromTag(ItemTags.ORES_NICKEL), RealMinerals.NICKEL_INGOT.get(), 0.7F, 200).addCriterion("has_nickel_ore", hasItem(ItemTags.ORES_NICKEL)).build(consumer,   new ResourceLocation(RealMinerals.MODID, "nickel_ingot_from_smelting_ore"));
        CookingRecipeBuilder.blastingRecipe(Ingredient.fromTag(ItemTags.DUSTS_NICKEL), RealMinerals.NICKEL_INGOT.get(), 0.7F, 100).addCriterion("has_nickel_ore", hasItem(ItemTags.DUSTS_NICKEL)).build(consumer, new ResourceLocation(RealMinerals.MODID, "nickel_ingot_from_blasting_dust"));
        CookingRecipeBuilder.smeltingRecipe(Ingredient.fromTag(ItemTags.DUSTS_NICKEL), RealMinerals.NICKEL_INGOT.get(), 0.7F, 200).addCriterion("has_nickel_ore", hasItem(ItemTags.DUSTS_NICKEL)).build(consumer, new ResourceLocation(RealMinerals.MODID, "nickel_ingot_from_smelting_dust"));
        ShapedRecipeBuilder.shapedRecipe(RealMinerals.NICKEL_INGOT.get()).key('#', ItemTags.NUGGETS_NICKEL).patternLine("###").patternLine("###").patternLine("###").addCriterion("has_nickel_nugget", hasItem(ItemTags.NUGGETS_NICKEL)).build(consumer, new ResourceLocation(RealMinerals.MODID, "nickel_ingot_from_nuggets"));
        ShapedRecipeBuilder.shapedRecipe(RealMinerals.NICKEL_BLOCK.ITEM.get()).key('#', ItemTags.INGOTS_NICKEL).patternLine("###").patternLine("###").patternLine("###").addCriterion("has_nickel_ingot", hasItem(ItemTags.INGOTS_NICKEL)).build(consumer, new ResourceLocation(RealMinerals.MODID, "nickel_block_from_ingots"));
        ShapelessRecipeBuilder.shapelessRecipe(RealMinerals.NICKEL_INGOT.get(), 9).addIngredient(ItemTags.STORAGE_NICKEL).addCriterion("has_nickel_block", hasItem(ItemTags.STORAGE_NICKEL)).build(consumer, new ResourceLocation(RealMinerals.MODID, "nickel_ingot_from_block"));
        ShapelessRecipeBuilder.shapelessRecipe(RealMinerals.NICKEL_NUGGET.get(), 9).addIngredient(ItemTags.INGOTS_NICKEL).addCriterion("has_nickel_ingot", hasItem(ItemTags.INGOTS_NICKEL)).build(consumer, new ResourceLocation(RealMinerals.MODID, "nickel_nugget_from_ingot"));

        CrusherRecipeBuilder.crushingRecipe(Ingredient.fromTag(ItemTags.ORES_PLATINUM), RealMinerals.PLATINUM_DUST.get(), 2).build(consumer, new ResourceLocation(RealMinerals.MODID, "platinum_dust_from_ore"));
        CrusherRecipeBuilder.crushingRecipe(Ingredient.fromTag(ItemTags.INGOTS_PLATINUM), RealMinerals.PLATINUM_DUST.get()).build(consumer, new ResourceLocation(RealMinerals.MODID, "platinum_dust_from_ingot"));
        CookingRecipeBuilder.blastingRecipe(Ingredient.fromTag(ItemTags.ORES_PLATINUM), RealMinerals.PLATINUM_INGOT.get(), 0.7F, 100).addCriterion("has_platinum_ore", hasItem(ItemTags.ORES_PLATINUM)).build(consumer,   new ResourceLocation(RealMinerals.MODID, "platinum_ingot_from_blasting_ore"));
        CookingRecipeBuilder.smeltingRecipe(Ingredient.fromTag(ItemTags.ORES_PLATINUM), RealMinerals.PLATINUM_INGOT.get(), 0.7F, 200).addCriterion("has_platinum_ore", hasItem(ItemTags.ORES_PLATINUM)).build(consumer,   new ResourceLocation(RealMinerals.MODID, "platinum_ingot_from_smelting_ore"));
        CookingRecipeBuilder.blastingRecipe(Ingredient.fromTag(ItemTags.DUSTS_PLATINUM), RealMinerals.PLATINUM_INGOT.get(), 0.7F, 100).addCriterion("has_platinum_ore", hasItem(ItemTags.DUSTS_PLATINUM)).build(consumer, new ResourceLocation(RealMinerals.MODID, "platinum_ingot_from_blasting_dust"));
        CookingRecipeBuilder.smeltingRecipe(Ingredient.fromTag(ItemTags.DUSTS_PLATINUM), RealMinerals.PLATINUM_INGOT.get(), 0.7F, 200).addCriterion("has_platinum_ore", hasItem(ItemTags.DUSTS_PLATINUM)).build(consumer, new ResourceLocation(RealMinerals.MODID, "platinum_ingot_from_smelting_dust"));
        ShapedRecipeBuilder.shapedRecipe(RealMinerals.PLATINUM_INGOT.get()).key('#', ItemTags.NUGGETS_PLATINUM).patternLine("###").patternLine("###").patternLine("###").addCriterion("has_platinum_nugget", hasItem(ItemTags.NUGGETS_PLATINUM)).build(consumer, new ResourceLocation(RealMinerals.MODID, "platinum_ingot_from_nuggets"));
        ShapedRecipeBuilder.shapedRecipe(RealMinerals.PLATINUM_BLOCK.ITEM.get()).key('#', ItemTags.INGOTS_PLATINUM).patternLine("###").patternLine("###").patternLine("###").addCriterion("has_platinum_ingot", hasItem(ItemTags.INGOTS_PLATINUM)).build(consumer, new ResourceLocation(RealMinerals.MODID, "platinum_block_from_ingots"));
        ShapelessRecipeBuilder.shapelessRecipe(RealMinerals.PLATINUM_INGOT.get(), 9).addIngredient(ItemTags.STORAGE_PLATINUM).addCriterion("has_platinum_block", hasItem(ItemTags.STORAGE_PLATINUM)).build(consumer, new ResourceLocation(RealMinerals.MODID, "platinum_ingot_from_block"));
        ShapelessRecipeBuilder.shapelessRecipe(RealMinerals.PLATINUM_NUGGET.get(), 9).addIngredient(ItemTags.INGOTS_PLATINUM).addCriterion("has_platinum_ingot", hasItem(ItemTags.INGOTS_PLATINUM)).build(consumer, new ResourceLocation(RealMinerals.MODID, "platinum_nugget_from_ingot"));

        CrusherRecipeBuilder.crushingRecipe(Ingredient.fromTag(ItemTags.ORES_SILVER), RealMinerals.SILVER_DUST.get(), 2).build(consumer, new ResourceLocation(RealMinerals.MODID, "silver_dust_from_ore"));
        CrusherRecipeBuilder.crushingRecipe(Ingredient.fromTag(ItemTags.INGOTS_SILVER), RealMinerals.SILVER_DUST.get()).build(consumer, new ResourceLocation(RealMinerals.MODID, "silver_dust_from_ingot"));
        CookingRecipeBuilder.blastingRecipe(Ingredient.fromTag(ItemTags.ORES_SILVER), RealMinerals.SILVER_INGOT.get(), 0.7F, 100).addCriterion("has_silver_ore", hasItem(ItemTags.ORES_SILVER)).build(consumer,   new ResourceLocation(RealMinerals.MODID, "silver_ingot_from_blasting_ore"));
        CookingRecipeBuilder.smeltingRecipe(Ingredient.fromTag(ItemTags.ORES_SILVER), RealMinerals.SILVER_INGOT.get(), 0.7F, 200).addCriterion("has_silver_ore", hasItem(ItemTags.ORES_SILVER)).build(consumer,   new ResourceLocation(RealMinerals.MODID, "silver_ingot_from_smelting_ore"));
        CookingRecipeBuilder.blastingRecipe(Ingredient.fromTag(ItemTags.DUSTS_SILVER), RealMinerals.SILVER_INGOT.get(), 0.7F, 100).addCriterion("has_silver_ore", hasItem(ItemTags.DUSTS_SILVER)).build(consumer, new ResourceLocation(RealMinerals.MODID, "silver_ingot_from_blasting_dust"));
        CookingRecipeBuilder.smeltingRecipe(Ingredient.fromTag(ItemTags.DUSTS_SILVER), RealMinerals.SILVER_INGOT.get(), 0.7F, 200).addCriterion("has_silver_ore", hasItem(ItemTags.DUSTS_SILVER)).build(consumer, new ResourceLocation(RealMinerals.MODID, "silver_ingot_from_smelting_dust"));
        ShapedRecipeBuilder.shapedRecipe(RealMinerals.SILVER_INGOT.get()).key('#', ItemTags.NUGGETS_SILVER).patternLine("###").patternLine("###").patternLine("###").addCriterion("has_silver_nugget", hasItem(ItemTags.NUGGETS_SILVER)).build(consumer, new ResourceLocation(RealMinerals.MODID, "silver_ingot_from_nuggets"));
        ShapedRecipeBuilder.shapedRecipe(RealMinerals.SILVER_BLOCK.ITEM.get()).key('#', ItemTags.INGOTS_SILVER).patternLine("###").patternLine("###").patternLine("###").addCriterion("has_silver_ingot", hasItem(ItemTags.INGOTS_SILVER)).build(consumer, new ResourceLocation(RealMinerals.MODID, "silver_block_from_ingots"));
        ShapelessRecipeBuilder.shapelessRecipe(RealMinerals.SILVER_INGOT.get(), 9).addIngredient(ItemTags.STORAGE_SILVER).addCriterion("has_silver_block", hasItem(ItemTags.STORAGE_SILVER)).build(consumer, new ResourceLocation(RealMinerals.MODID, "silver_ingot_from_block"));
        ShapelessRecipeBuilder.shapelessRecipe(RealMinerals.SILVER_NUGGET.get(), 9).addIngredient(ItemTags.INGOTS_SILVER).addCriterion("has_silver_ingot", hasItem(ItemTags.INGOTS_SILVER)).build(consumer, new ResourceLocation(RealMinerals.MODID, "silver_nugget_from_ingot"));

        CrusherRecipeBuilder.crushingRecipe(Ingredient.fromTag(ItemTags.ORES_TIN), RealMinerals.TIN_DUST.get(), 2).build(consumer, new ResourceLocation(RealMinerals.MODID, "tin_dust_from_ore"));
        CrusherRecipeBuilder.crushingRecipe(Ingredient.fromTag(ItemTags.INGOTS_TIN), RealMinerals.TIN_DUST.get()).build(consumer, new ResourceLocation(RealMinerals.MODID, "tin_dust_from_ingot"));
        CookingRecipeBuilder.blastingRecipe(Ingredient.fromTag(ItemTags.ORES_TIN), RealMinerals.TIN_INGOT.get(), 0.7F, 100).addCriterion("has_tin_ore", hasItem(ItemTags.ORES_TIN)).build(consumer,   new ResourceLocation(RealMinerals.MODID, "tin_ingot_from_blasting_ore"));
        CookingRecipeBuilder.smeltingRecipe(Ingredient.fromTag(ItemTags.ORES_TIN), RealMinerals.TIN_INGOT.get(), 0.7F, 200).addCriterion("has_tin_ore", hasItem(ItemTags.ORES_TIN)).build(consumer,   new ResourceLocation(RealMinerals.MODID, "tin_ingot_from_smelting_ore"));
        CookingRecipeBuilder.blastingRecipe(Ingredient.fromTag(ItemTags.DUSTS_TIN), RealMinerals.TIN_INGOT.get(), 0.7F, 100).addCriterion("has_tin_ore", hasItem(ItemTags.DUSTS_TIN)).build(consumer, new ResourceLocation(RealMinerals.MODID, "tin_ingot_from_blasting_dust"));
        CookingRecipeBuilder.smeltingRecipe(Ingredient.fromTag(ItemTags.DUSTS_TIN), RealMinerals.TIN_INGOT.get(), 0.7F, 200).addCriterion("has_tin_ore", hasItem(ItemTags.DUSTS_TIN)).build(consumer, new ResourceLocation(RealMinerals.MODID, "tin_ingot_from_smelting_dust"));
        ShapedRecipeBuilder.shapedRecipe(RealMinerals.TIN_INGOT.get()).key('#', ItemTags.NUGGETS_TIN).patternLine("###").patternLine("###").patternLine("###").addCriterion("has_tin_nugget", hasItem(ItemTags.NUGGETS_TIN)).build(consumer, new ResourceLocation(RealMinerals.MODID, "tin_ingot_from_nuggets"));
        ShapedRecipeBuilder.shapedRecipe(RealMinerals.TIN_BLOCK.ITEM.get()).key('#', ItemTags.INGOTS_TIN).patternLine("###").patternLine("###").patternLine("###").addCriterion("has_tin_ingot", hasItem(ItemTags.INGOTS_TIN)).build(consumer, new ResourceLocation(RealMinerals.MODID, "tin_block_from_ingots"));
        ShapelessRecipeBuilder.shapelessRecipe(RealMinerals.TIN_INGOT.get(), 9).addIngredient(ItemTags.STORAGE_TIN).addCriterion("has_tin_block", hasItem(ItemTags.STORAGE_TIN)).build(consumer, new ResourceLocation(RealMinerals.MODID, "tin_ingot_from_block"));
        ShapelessRecipeBuilder.shapelessRecipe(RealMinerals.TIN_NUGGET.get(), 9).addIngredient(ItemTags.INGOTS_TIN).addCriterion("has_tin_ingot", hasItem(ItemTags.INGOTS_TIN)).build(consumer, new ResourceLocation(RealMinerals.MODID, "tin_nugget_from_ingot"));

    }
}
